language: r
warnings_are_errors: false
sudo: required

cache: apt

notifications:
  email:
    on_success: change
    on_failure: change

install:
  - Rscript -e 'install.packages("devtools", repos = "http://cran.rstudio.com")'

r_binary_packages:
  - devtools

r_github_packages:
  - jimhester/covr
  - jimhester/lintr

after_success:
  - Rscript -e 'library(covr);codecov()'
  - Rscript -e 'lintr::lint_package()'
